version: '3'

services:
  app:
    build: .
    ports:
      - '${PORT:-3001}:3001'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - '.:/usr/app'
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - .docker/data:/data/db